version: "3.8"

services:
  web:
    image: php:8.1-apache
    container_name: my_php_apache
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: my_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: dreampastry
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"  # évite le conflit avec ton MySQL local

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD:
    ports:
      - "8081:80"
    depends_on:
      - db

  app:
    build: .
    container_name: dreampastry-app
    restart: always
    ports:
      - "8501:8501"  # ton app Streamlit
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: dreampastry
      OLLAMA_HOST: http://ollama:11434
    volumes:
      - ~/.ollama:/root/.ollama
      - ./Research:/app/Research  # partage tes fichiers PDF vers le conteneur

  ollama:
    image: ollama/ollama:0.12.3
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama
    restart: always

volumes:
  db_data:
